sudo: false
language: python
python:
  - 3.5
install:
    - pip install -r requirements.txt
script:
  - coverage run -m pytest
  - coverage report stackoverflowlite/**/*.py stackoverflowlite/views.py
  - coveralls
after_sucess:
  - coveralls
